import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Generated by create next app",
  icons : {
    icon : "/favicon.svg"
  }
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <Head>
        <link rel="shortcut icon" href="./favicon.svg" />
      </Head> */}
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}

