import { Inter } from "next/font/google";
import "../globals.css";
import SearchHeader from "@/components/SearchHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Generated by create next app",
  icons : {
    icon : "/favicon.svg"
  }
};

export default function SearchLayout({ children }) {
  return (
    <>
        <div className={inter.className}>
            <SearchHeader />
          {children}
          {/* <Footer /> */}
        </div>
    </>
  );
}

